Pls merge me :( but don't actually because code is not done yet
Aiz0/operation-cute-octopus pull request #27
Opened 2021-05-11 14:18 UTC by BarbaFin

2021-05-11 14:39 UTC, Aiz0 commented
:upside_down_face:

2021-05-11 14:41 UTC, Aiz0 commented
kan inte merga just nu för att du har ändrat tillbaka mycket kod som vi uppdaterat

2021-05-12 10:59 UTC, Aiz0 requested changes
Går inte att

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/Shop/SwitchCamera.cs
> +        canvas2.SetActive(false);
what. why
why not move the camera?
why do you do this

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/Shop/ShopController.cs
> +    }
Använd ny load scene prefab med scene transition.

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/Shop/ShopController.cs
> +    public Text[] statsText;
Sluta med public

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/Shop/ShopController.cs
> +    public int maxInk;
Sluta med public

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/Obstacles/ObstacleMoveSimple.cs
> +        rb2D.velocity = gameController.GetDirection() * gameController.GetSpeed() * speedMultiplier;
döp om igen

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/Obstacles/HurtBox.cs
> +}
använd det nya sättet. det du tog bort.

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> +    public void increaseSpeed()
du skulle ju döpa om den til IncreaseSpeed()

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> -    private IEnumerator SlowDown()
Varför tog du bort denna funktion?

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> +        Destroy(player);
Varför tog du bort player death animation?

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> +        inkText.text = ink.ToString();
varför gör du detta här när setInk redan gör detta?

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> +        }
Varför inte bara säga att det värdet man får om "Ink" inte finns är 1.

Varför gör du detta varje gång spelaren reloadar och inte i början och använder maxInk?

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> +            healthText.text = health.ToString();
Samma som ink grejen

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
>      }
Sluta

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> -        return baseObstacle;
NEj

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> -    }
varför då?

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> +        UpdateInk();
NEj

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> -        SetInk(maxInk);
nej

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> +        scoreInterval = spawner.distanceBetweenPatterns / speed;
vi vill använda oss av det nya sättet

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> +    public GameObject parent;
Player var redan en variabel här.

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> +    public float speed = 1;
nej

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> -    private bool allowOtherSpawns = true;
nej

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Animations/Arrow/hej.anim
> +  m_Name: hej
varför?

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Animations/Arrow/hej.anim
> +      value: {fileID: 21300000, guid: a8629cf4231fa074b93a5a02504c7a4b, type: 3}
vad?

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Animations/Player.controller
> +  - m_Name: New Trigger
Tar du bort Dead animationen?

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Animations/Player.controller
> +  m_Name: TEST
hmmm

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Animations/Player_swim.anim
> +  m_Events: []
hmmmmmmmmm

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> +            parent.transform.GetChild(0).gameObject.SetActive(false);
varför har du en loop om du inte använder dig av variablen eller blir ett annat gameobject på index 0 när du sätter den till inactive?

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> +    public void ChangeSkins()
Varför görs detta i gamecontroller?
Detta ska göras i ett script på spelaren.
Inget annat objekt bryr sig om vad för skin vi har.

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> +            parent.transform.GetChild(0).gameObject.SetActive(true);
är du helt säker på att det är så här vi vill göra.
Att det inte finns något bättre sätt
Att vi måste skapa en ny animation varje gång.

Är du helt säker på att det inte går att byta ut vilka sprites som änvänds vid animationen?
Det kommer bli väldigt jobbigt att lägga in nya sprites om det är så här vi ska göra.

2021-05-12 10:59 UTC, Aiz0 commented on src/Assets/Scripts/GameController.cs
> +        }
varför gör du så här?

2021-05-12 13:14 UTC, BarbaFin commented on src/Assets/Scripts/GameController.cs
> +        }
För att jag vill?

2021-05-12 13:14 UTC, BarbaFin commented on src/Assets/Scripts/GameController.cs
> +            parent.transform.GetChild(0).gameObject.SetActive(true);
Ja, jag hittar inget bättre sätt.

2021-05-12 13:14 UTC, BarbaFin commented on src/Assets/Scripts/GameController.cs
> +    public void ChangeSkins()
För att jag vill.

2021-05-12 13:14 UTC, BarbaFin commented on src/Assets/Scripts/GameController.cs
> +            parent.transform.GetChild(0).gameObject.SetActive(false);
Tror det var till för senare.

2021-05-12 13:15 UTC, BarbaFin commented on src/Assets/Scripts/Shop/SwitchCamera.cs
> +        canvas2.SetActive(false);
För att det inte ville så testade olika sätt.

2021-05-12 13:16 UTC, BarbaFin commented on src/Assets/Scripts/Shop/ShopController.cs
> +    public Text[] statsText;
Som tidigare nämt är detta inte den färdiga koden och för tillfället får jag det bara att fungera innan något annat. Det är så jag arbetar.

2021-05-12 13:16 UTC, BarbaFin commented on src/Assets/Scripts/Shop/ShopController.cs
> +    public int maxInk;
Som tidigare

2021-05-12 13:17 UTC, BarbaFin commented on src/Assets/Scripts/GameController.cs
> +    public void increaseSpeed()
Jag vet, tror bara det var jag som tänkte på annat och tryckte fel.

2021-05-12 13:18 UTC, BarbaFin commented on src/Assets/Scripts/GameController.cs
>      }
Nej :)

2021-05-12 13:18 UTC, BarbaFin commented on src/Assets/Scripts/GameController.cs
> +        UpdateInk();
Jo?

2021-05-12 13:18 UTC, BarbaFin commented on src/Assets/Scripts/GameController.cs
> -        SetInk(maxInk);
Jo?

2021-05-12 13:19 UTC, BarbaFin commented on src/Assets/Animations/Player.controller
> +  - m_Name: New Trigger
Ja, för att det inte kommer att hänga ihop när anim sitter som child :)

2021-05-12 13:26 UTC, BarbaFin commented on src/Assets/Animations/Player_swim.anim
> +  m_Events: []
Vet inte ens vad detta är

2021-05-12 13:34 UTC, BarbaFin commented on src/Assets/Scripts/GameController.cs
> +        Destroy(player);
För det kommer ej funka? Men kan försöka

2021-05-19 07:40 UTC, closed without merging